### ISSUE TITLE
[Bug report] MLSearch can not be disabled

### ISSUE THREAD

**Issue by andrew-kurochkin** [Actual-Chat/actual-chat#2155]
May 23, 24.
Quote:
- сделайте что-нибудь плиз с конфигурацией поиска, он спамит ошибками и не дает дебажить. причем ему плевать, что я уже отключил поиск. он все равно спамит

**Comment by AlexUstinov** [comment]
ML search has its own setting to disable.

**Comment by andrew-kurochkin** [comment]
appsettings.json / appsettings.Development.json effectively disables MLSearch.
"MLSearchSettings": {
    "IsEnabled": false
}
Note:
If prior to restart the ML search was enabled it produces several messages mentioning ActualChat.Queues.Nats.NatsQueueProcessor(MLSearchBackend)[0] . However there are very few of those and it does not seem to be an issue.
