### ISSUE TITLE
[Bug report] Wrong author attribution in the chats list

### ISSUE THREAD

**Issue by andrew-kurochkin** [Actual-Chat/actual-chat#2161]
June 6, 24.
Confirmed. Needs investigation.

Issue:
- See attachments: A message sent by Andrey Yakunin is attributed to Sergey Yakunin.

![Image](https://github.com/Actual-Chat/actual-chat/assets/3794323/52a0d483-1ff6-4dc2-88ae-273e7a71bd43)

In chat list chat news repor that the message was sent from Sergey, and this is wrong.
![Image](https://github.com/Actual-Chat/actual-chat/assets/3794323/b1b19790-e6b5-4e45-8cff-9a3f4fae96e0)

**Comment by crui3er** [comment]
Can't reproduce.
