### ISSUE TITLE
[Bug report] Notifications routing issue

### ISSUE THREAD

**Issue by andrew-kurochkin** [Actual-Chat/actual-chat#2166]
May 30, 24.
Mobile
Quote:
- у меня какая-то лютая срань с нотификациями, подскажите, где я не так делаю
я на мак поставил айфоновское приложение из апп стора,. все легально, никаких костылей
и по ошибке залогинился личным аккаунтом через apple id
разлогинился, залогинился нашим аккаунтом
но нотификации похоже прилетают на на предыдущий аккаунт
либо еще что-то глючит
ну т.е. я не должен видеть нотификации (пуши) на сообщения, которые сам же и отправляю
из этого я делаю вывод. что возможно они прилетают на предыдущий аккаунт каким-то глючным образом

**Comment by crui3er** [comment]
Device should be unregistered on SignOut.
