### ISSUE TITLE
Onboarding avatar upload is not working.

### ISSUE THREAD

**Issue by andrew-kurochkin** [Actual-Chat/actual-chat#2168]
June 6, 24.
Mobile App. Android
Issues:
- Application is reloaded if you try to upload avatar.
- Save button does not work on Avatar change.
Note: 
- As at the moment of the report it was working in dev and was broken in prod. 
- Close once fix is in prod.

**Comment by crui3er** [comment]
Can't reproduce. Added possibility to restart onboarding process.
