### ISSUE TITLE
Notification resent on reaction added

### ISSUE THREAD

**Issue by andrew-kurochkin** [Actual-Chat/actual-chat#2173]
Repro:
- Notification sent on a message
- Someone else adds a reaction.
- Notification is being resent

**Comment by crui3er** [comment]
I did a test and it showed that message text is quted and prefixed with reaction sign
![Image](https://github.com/Actual-Chat/actual-chat/assets/20703715/1bdcff1e-4d19-4bcf-aa80-66275a5d0cea)

**Comment by crui3er** [comment]
Can not reproduce
