### ISSUE TITLE
[Bug report] [UI] Buttons transparency issues

### ISSUE THREAD

**Issue by andrew-kurochkin** [Actual-Chat/actual-chat#2183]
June 10, 24.

![Image](https://github.com/Actual-Chat/actual-chat/assets/3794323/145904be-2f05-486c-b72a-366ff22754f1)
![Image](https://github.com/Actual-Chat/actual-chat/assets/3794323/23ad8c07-5f52-4d43-9caf-4c4e68f1f5df)

**Comment by alexis-kochetov** [comment]
Already changed
