### ISSUE TITLE
[Bug report][Mobile] Chat does not open on a redirect from a notification

### ISSUE THREAD

**Issue by andrew-kurochkin** [Actual-Chat/actual-chat#2206]
June 18, 24
+ Attachements

[log_actual_chat_20240618_22.49.05.txt](https://github.com/user-attachments/files/15945750/log_actual_chat_20240618_22.49.05.txt)

https://github.com/Actual-Chat/actual-chat/assets/3794323/65d12cfa-fdaa-4231-87b0-78517a198076

Quote:
Сейчас вот такой баг с панеля словил.
Тайну на нотификацию, потом открылось приложение на списке чатов с правильно выбранным чатом, но средняя панель не открылась. Повторное нажатие на чат айтем не открывало среднюю панель. Скайпы тоже не позволяли открыть среднюю панель.

**Comment by crui3er** [comment]
Not reproducible. Saw this issue only once and reported this issue.
