### ISSUE TITLE
bug: 1 unread message on start

### ISSUE THREAD

**Issue by frolyo** [Actual-Chat/actual-chat#332]
![image](https://user-images.githubusercontent.com/4425748/182104360-3fbd80d8-06d3-47de-9ec0-30536a063d4e.png)

#### Steps to reproduce

1. Start chat locally
2. Open localhost:7080 in browser
3. See the result

**Comment by FrolYo** [comment]
![image](https://user-images.githubusercontent.com/4425748/182104360-3fbd80d8-06d3-47de-9ec0-30536a063d4e.png)

#### Steps to reproduce

1. Start chat locally
2. Open localhost:7080 in browser
3. See the result
