### ISSUE TITLE
Clicking on user link from user settings screen opens empty screen

### ISSUE THREAD

**Issue by frolyo** [Actual-Chat/actual-chat#776]
**Steps to reproduce:**

1. Open user settings by clicking on avatar icon in the left bottom corner
2. Click on the link
![image](https://user-images.githubusercontent.com/4425748/209574247-9f3848ca-6160-4677-82d8-686d9f25b02c.png)

**Actual Result:**
It opens empty screen

**Comment by crui3er** [comment]
UI is reworked. Now it opens 'share your contact' modal.
