### ISSUE TITLE
iOS safari - Transcribing does not start though recording is in progress

### ISSUE THREAD

**Issue by frolyo** [Actual-Chat/actual-chat#996]
Steps to reproduce (not every time but quite often):

1. All the steps must be done as fast as possible to reproduce the issue
2. Refresh page
3. Start recording
4. Grant mic permission
5. Start talking and see that there is no transcription appearing

Expected result:
Transcribing is started

Actual result:
Transcribing does not start, although microphone is captured and recording is in progress
[dev.actual.chat-1676896886020.log](https://github.com/Actual-Chat/actual-chat/files/10784721/dev.actual.chat-1676896886020.log)

**Comment by alexyakunin** [comment]
Still intact?
